name: Deploy Versioning Test

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          dry_run: "true"
          release_branches: "release"
          pre_release_branches: "beta"
          append_to_pre_release_tag: "beta"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Change Log and Page
        run: |
          git tag | grep 'beta' | xargs -r git tag -d
          pnpm changelog 
          pnpm changelog:page
          git fetch --tags

      - name: Display first 100 lines of CHANGELOG.md
        run: cat CHANGELOG.md | sed -n '1,100p'

      - name: Remove local beta tags
        run: git tag | grep 'beta' | xargs -r git tag -d

      - name: Generate changelog info and set to output
        id: changelog
        run: |
          [ -f  CHANGELOG.md ] && rm CHANGELOG.md

          changelog=$(pnpm -s changelog:latest-stdout | sed '1,3d')
          version=$(git describe --tags --abbrev=0)
          name=$(node ./scripts/.package-props.js displayName)

          echo "# [$name] New version released!" >> temp.txt
          echo "" >> temp.txt
          echo "Version: $version" >> temp.txt
          echo "" >> temp.txt
          echo "$changelog" >> temp.txt

          echo 'message<<EOF' >> $GITHUB_OUTPUT
          cat temp.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Display changelog message
        run: echo "${{ steps.changelog.outputs.message }}"

      - name: Discord notification
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "Debug Message: ${{ steps.changelog.outputs.message }}"
